import React, { useState } from "react";
import { getSymbolDisplayMode } from "../../../engine/display/displaySettings.js";

const SYMBOLS = {
  "relationships": "👨‍👩‍👧", "people": "👥", "love care": "💖", "greeting": "👋", "social words": "💬", "family": "👨‍👩‍👧", "friends": "🧑‍🤝‍🧑", "help comfort": "🤗", "feelings together": "❤️", "school people": "🧑‍🏫",
  "feelings": "😊", "happy feelings": "😊", "sad feelings": "😢", "mad feelings": "😠", "scared feelings": "😨", "body feelings": "🤕", "energy": "⚡", "calm": "😌", "social feelings": "🫶", "needs with feelings": "🆘",
  "food and drink": "🍎", "fruit": "🍎", "produce": "🥕", "snacks": "🍪", "meals": "🍽️", "breakfast": "🥣", "fast food": "🍟", "drinks": "🥤", "sweets": "🍬", "hot food": "🍲", "cold food": "🧊",
  "mcdonalds": "🍟", "burger king": "🍔", "wendys": "🍔", "chick fil a": "🍗", "taco bell": "🌮", "pizza chains": "🍕", "subway": "🥪", "kfc": "🍗", "popeyes": "🍗", "sonic": "🥤", "dairy queen": "🍦", "fast food favorites": "⭐",
  "places": "🏠", "school": "🏫", "actions": "🏃", "things": "🧸", "body and health": "🩺", "questions": "❓", "recents": "🕘", "favorites": "⭐", "search": "🔎", "emergency": "🚨",

  "mom": "👩", "dad": "👨", "grandma": "👵", "grandpa": "👴", "brother": "👦", "sister": "👧", "aunt": "👩", "uncle": "👨", "cousin": "🧒", "baby": "👶", "teacher": "🧑‍🏫", "doctor": "🧑‍⚕️", "nurse": "🧑‍⚕️", "friend": "🧑", "classmate": "🧑", "helper": "🤝", "principal": "🏫", "bus driver": "🚌", "therapist": "🧑‍⚕️", "speech teacher": "🗣️", "student": "🧒",
  "i love you": "💖", "love": "💖", "hug": "🤗", "can i have a hug": "🤗", "kiss": "😘", "hold hand": "🤝", "stay with me": "🫶", "sit with me": "🪑", "help me": "🆘", "i miss you": "💭", "i need you": "🫶", "thank you": "🙏", "please": "🙂", "hi": "👋", "hello": "👋", "bye": "👋", "good morning": "🌞", "good night": "🌙", "see you later": "👋", "how are you": "❓", "i'm okay": "👌", "you're welcome": "🙂", "i'm sorry": "😔", "sorry": "😔", "excuse me": "🙋", "nice to see you": "😊", "come here": "👋", "look at me": "👀", "listen": "👂", "my turn": "☝️", "your turn": "👉", "share": "🤲", "play with me": "🛝", "talk to me": "🗣️", "i need space": "🫧", "stop please": "🛑", "again": "🔁", "more": "➕", "all done": "✅", "finished": "✅",

  "happy": "😊", "excited": "🤩", "proud": "😌", "silly": "😜", "funny": "😂", "good": "👍", "great": "🌟", "safe": "🛡️", "okay": "👌", "i like it": "👍", "i love it": "💖", "fun": "🎉", "sad": "😢", "lonely": "🥺", "miss you": "💭", "cry": "😭", "upset": "☹️", "disappointed": "😞", "not okay": "☹️", "hurt feelings": "💔", "i need hug": "🤗", "mad": "😠", "angry": "😡", "frustrated": "😣", "too much": "⚠️", "no": "❌", "i don't want": "🚫", "i need break": "⏸️", "quiet": "🤫", "wait": "⏳", "not fair": "⚖️", "scared": "😨", "worried": "😟", "nervous": "😬", "afraid": "😨", "unsafe": "⚠️", "too loud": "🔊", "dark": "🌑", "hurt": "🤕",
  "sick": "🤒", "tired": "😴", "hungry": "🍽️", "thirsty": "🥤", "hot": "🥵", "cold": "🥶", "pain": "⚡", "head hurts": "🤕", "stomach hurts": "🤢", "ear hurts": "👂", "mouth hurts": "👄", "bathroom": "🚽", "medicine": "💊", "rest": "🛏️", "water": "💧", "sleepy": "😴", "awake": "☀️", "wiggly": "🌀", "busy": "🐝", "fast": "⚡", "slow": "🐢", "break": "⏸️", "play": "🎮", "outside": "🌳", "inside": "🏠", "space": "🫧", "breathe": "🌬️", "blanket": "🛏️", "dark room": "🌑", "music": "🎵", "embarrassed": "😳", "shy": "🫣",

  "apple": "🍎", "banana": "🍌", "orange": "🍊", "grapes": "🍇", "strawberry": "🍓", "blueberry": "🫐", "watermelon": "🍉", "pineapple": "🍍", "peach": "🍑", "pear": "🍐", "mango": "🥭", "raspberry": "🍓", "blackberry": "🫐", "cherry": "🍒", "fruit cup": "🍎", "applesauce": "🥣", "raisins": "🍇",
  "carrot": "🥕", "corn": "🌽", "peas": "🟢", "green beans": "🫘", "broccoli": "🥦", "potato": "🥔", "sweet potato": "🍠", "cucumber": "🥒", "tomato": "🍅", "lettuce": "🥬", "salad": "🥗", "pickle": "🥒", "avocado": "🥑", "celery": "🥬", "vegetables": "🥦",
  "chips": "🍟", "gummies": "🍬", "fruit snacks": "🍬", "crackers": "🫓", "cookies": "🍪", "cookie": "🍪", "pretzels": "🥨", "popcorn": "🍿", "granola bar": "🍫", "cheese stick": "🧀", "yogurt": "🥣", "pudding": "🍮", "goldfish": "🐟", "trail mix": "🥜", "cereal bar": "🍫", "rice cake": "🍘", "snack": "🍪",
  "chicken nuggets": "🍗", "french fries": "🍟", "pizza": "🍕", "sandwich": "🥪", "mac and cheese": "🧀", "hot dog": "🌭", "hamburger": "🍔", "cheeseburger": "🍔", "pasta": "🍝", "spaghetti": "🍝", "rice": "🍚", "chicken": "🍗", "soup": "🍲", "tacos": "🌮", "taco": "🌮", "quesadilla": "🌮", "grilled cheese": "🥪", "meatballs": "🍝", "dinner": "🍽️", "chicken sandwich": "🥪", "milkshake": "🥤", "ice cream": "🍦", "apple slices": "🍎", "soda": "🥤", "lemonade": "🍋", "ketchup": "🍅", "sauce": "🥫", "kids meal": "🍽️",
  "cereal": "🥣", "oatmeal": "🥣", "pancakes": "🥞", "waffles": "🧇", "eggs": "🍳", "toast": "🍞", "bagel": "🥯", "muffin": "🧁", "milk": "🥛", "juice": "🧃", "breakfast bar": "🍫", "donut": "🍩", "hash browns": "🥔", "bacon": "🥓",
  "drink": "🥤", "apple juice": "🧃", "orange juice": "🧃", "chocolate milk": "🥛", "smoothie": "🥤", "sports drink": "🥤", "hot chocolate": "☕", "straw": "🥤", "cup": "🥤", "more drink": "🥤", "ice": "🧊", "candy": "🍬", "cake": "🍰", "cupcake": "🧁", "brownie": "🍫", "popsicle": "🍧", "chocolate": "🍫", "marshmallow": "🍬", "sweet": "🍬", "treat": "🍬", "too hot": "🥵", "cool down": "🌬️", "too cold": "🥶", "cold pizza": "🍕",

  "toy": "🧸", "tablet": "📱", "book": "📘", "ball": "⚽", "chair": "🪑", "bed": "🛏️", "door": "🚪", "light": "💡", "remote": "🎛️", "game": "🎮",
  "happy meal": "🍱",
  "mcflurry": "🍦",
  "ice cream cone": "🍦",
  "breakfast sandwich": "🥪",
  "whopper": "🍔",
  "onion rings": "🧅",
  "apple bites": "🍎",
  "frosty": "🍦",
  "waffle fries": "🍟",
  "chick fil a sauce": "🥫",
  "grilled nuggets": "🍗",
  "soft taco": "🌮",
  "crunchy taco": "🌮",
  "burrito": "🌯",
  "nachos": "🧀",
  "beans": "🫘",
  "beef": "🥩",
  "cheese pizza": "🍕",
  "pepperoni pizza": "🍕",
  "sausage pizza": "🍕",
  "breadsticks": "🥖",
  "cheesy bread": "🧀",
  "wings": "🍗",
  "slice": "🍕",
  "whole pizza": "🍕",
  "more pizza": "🍕",
  "turkey sandwich": "🥪",
  "ham sandwich": "🥪",
  "meatball sub": "🥪",
  "fried chicken": "🍗",
  "chicken tenders": "🍗",
  "mashed potatoes": "🥔",
  "biscuit": "🥐",
  "coleslaw": "🥗",
  "red beans and rice": "🫘",
  "corn dog": "🌭",
  "tater tots": "🥔",
  "slush": "🥤",
  "pretzel": "🥨",
  "chicken strips": "🍗",
  "blizzard": "🍦",
  "sundae": "🍨",
  "dilly bar": "🍦",
  "pretzel sticks": "🥨",

  "family people": "👨‍👩‍👧",
  "friend people": "🧑‍🤝‍🧑",
  "helper people": "🤝",
  "pronouns": "🙋",
  "groups": "👥",
  "love words": "💖",
  "hugs": "🤗",
  "kind words": "🙂",
  "missing someone": "💭",
  "care actions": "🫶",
  "praise": "👏",
  "greetings": "👋",
  "hello": "👋",
  "goodbye": "👋",
  "daily greetings": "🌞",
  "conversation starters": "💬",
  "polite words": "🙏",
  "turns": "🔁",
  "sharing": "🤲",
  "play words": "🎮",
  "space words": "🫧",
  "repair words": "🛠️",
  "conversation control": "🎛️",
  "parents": "👨‍👩‍👧",
  "grandparents": "👵",
  "siblings": "👦",
  "home family": "🏠",
  "family feelings": "❤️",
  "family actions": "🫶",
  "friend names": "🧑",
  "play together": "🛝",
  "school friends": "🏫",
  "sharing with friends": "🤲",
  "friend feelings": "❤️",
  "helpers": "🤝",
  "at home helpers": "🏠",
  "at school helpers": "🏫",
  "medical helpers": "🩺",
  "safety helpers": "🛡️",
  "ask for help": "🆘",
  "comfort": "🤗",
  "comfort people": "👥",
  "comfort actions": "🤗",
  "comfort items": "🧸",
  "comfort places": "🏠",
  "comfort words": "💬",
  "happy together": "😊",
  "sad together": "😢",
  "mad together": "😠",
  "scared together": "😨",
  "repair together": "🛠️",
  "teachers": "🧑‍🏫",
  "classmates": "👥",
  "school helpers": "🤝",
  "bus people": "🚌",
  "therapy people": "🗣️",
  "happy": "😊",
  "excited": "🤩",
  "proud": "😌",
  "silly": "😜",
  "good": "👍",
  "safe happy": "🛡️",
  "sad": "😢",
  "lonely": "🥺",
  "crying": "😭",
  "disappointed": "😞",
  "need comfort": "🤗",
  "mad": "😠",
  "angry": "😡",
  "frustrated": "😣",
  "too much": "⚠️",
  "need space": "🫧",
  "stop words": "🛑",
  "scared": "😨",
  "worried": "😟",
  "nervous": "😬",
  "unsafe": "⚠️",
  "loud dark": "🔊",
  "need safety": "🛡️",
  "hurt": "🤕",
  "sick": "🤒",
  "tired": "😴",
  "hungry thirsty": "🍽️",
  "temperature": "🌡️",
  "bathroom body": "🚽",
  "energy feelings": "⚡",
  "low energy": "😴",
  "high energy": "⚡",
  "wiggly": "🌀",
  "need break": "⏸️",
  "ready": "✅",
  "not ready": "⏸️",
  "calm tools": "😌",
  "quiet": "🤫",
  "space": "🫧",
  "breathing": "🌬️",
  "calm places": "🏠",
  "feeling needs": "🆘",
  "help needs": "🆘",
  "body needs": "🧍",
  "comfort needs": "🤗",
  "people needs": "👥",
  "stop needs": "🛑",
  "finish needs": "✅",
  "common fruit": "🍎",
  "berries": "🫐",
  "citrus": "🍊",
  "melon": "🍉",
  "tropical fruit": "🥭",
  "fruit cups": "🍎",
  "vegetables": "🥦",
  "crunchy produce": "🥕",
  "soft produce": "🍌",
  "potatoes": "🥔",
  "salads": "🥗",
  "dips": "🥫",
  "chips": "🍟",
  "gummies": "🍬",
  "crackers": "🫓",
  "cookies": "🍪",
  "bars": "🍫",
  "cold snacks": "🧊",
  "crunchy snacks": "🥨",
  "kid favorites": "⭐",
  "chicken meals": "🍗",
  "pizza meals": "🍕",
  "sandwich meals": "🥪",
  "pasta meals": "🍝",
  "soup rice": "🍲",
  "mexican foods": "🌮",
  "cereal": "🥣",
  "hot breakfast": "🥣",
  "bakery breakfast": "🥯",
  "eggs meat": "🍳",
  "breakfast drinks": "🥛",
  "breakfast snacks": "🍌",
  "water": "💧",
  "milk": "🥛",
  "juice": "🧃",
  "lemonade": "🍋",
  "smoothies": "🥤",
  "soda": "🥤",
  "hot drinks": "☕",
  "drink tools": "🥤",
  "candy": "🍬",
  "chocolate": "🍫",
  "cake": "🍰",
  "ice cream": "🍦",
  "pudding": "🍮",
  "frozen treats": "🍧",
  "hot meals": "🍲",
  "hot snacks": "🥨",
  "too hot": "🥵",
  "cold meals": "🥪",
  "cold drinks": "🧊",
  "frozen foods": "🍧",
  "too cold": "🥶",
  "cheerios": "🥣",
  "frosted flakes": "🥣",
  "lucky charms": "🥣",
  "fruit loops": "🥣",
  "cinnamon toast crunch": "🥣",
  "rice krispies": "🥣",
  "doritos": "🍟",
  "cheetos": "🍟",
  "pringles": "🍟",
  "goldfish": "🐟",
  "cheez it": "🫓",
  "oreos": "🍪",
  "oreo": "🍪",
  "m ms": "🍬",
  "skittles": "🍬",
  "welch's fruit snacks": "🍬",
  "scooby snacks": "🍬",
  "nutri grain bar": "🍫",
  "rice krispies treat": "🍫",
  "mandarin orange": "🍊",
  "clementine": "🍊",
  "grapefruit": "🍊",
  "lemon": "🍋",
  "lime": "🍋",
  "cantaloupe": "🍈",
  "honeydew": "🍈",
  "kiwi": "🥝",
  "coconut": "🥥",
  "papaya": "🥭",
  "ranch": "🥫",
  "hummus": "🥣",
  "cheese dip": "🧀",
  "salsa": "🥫",
  "guacamole": "🥑",
  "pizza rolls": "🍕",
  "hot pocket": "🥟",
  "lunchable": "🍱",

  // V5.19 generated full coverage for every current topic-tree label and leaf
  "adult": "🔹",
  "adults": "🔹",
  "all done hug": "🤗",
  "alone": "🥺",
  "animal crackers": "🫓",
  "awesome": "👍",
  "back hurts": "🤕",
  "baked potato": "🥔",
  "banana smoothie": "🥤",
  "be with me": "🙋",
  "beans and rice": "🍲",
  "bedroom": "😴",
  "bedtime": "🌙",
  "berry smoothie": "🥤",
  "berry yogurt": "🍎",
  "best friend": "👥",
  "better": "🔹",
  "big hug": "🤗",
  "birthday cake": "🍪",
  "blow on it": "🔹",
  "body": "🔹",
  "bottle": "🥤",
  "bottle water": "🥤",
  "bowl": "🥣",
  "boy": "👦",
  "bread": "📘",
  "breakfast biscuit": "🍳",
  "bring me": "🙋",
  "bubbles": "🔹",
  "buddy": "👥",
  "bus helper": "🚌",
  "butter": "🔹",
  "butter noodles": "🍝",
  "call": "🔹",
  "call dad": "👨",
  "call grandma": "👵",
  "call grandpa": "👴",
  "call mom": "👩",
  "car": "🚗",
  "caregiver": "👨‍👩‍👧",
  "cheese": "👤",
  "cheese puffs": "👤",
  "chewy": "👤",
  "chicken and rice": "🍗",
  "chicken soup": "🍗",
  "chili": "🍲",
  "chocolate bar": "🍫",
  "chocolate chip cookie": "🍪",
  "chocolate ice cream": "🍦",
  "chocolate pudding": "🔹",
  "cinnamon twists": "🔹",
  "class": "🧑‍🏫",
  "clean": "🔹",
  "close": "🫧",
  "coach": "🧑‍🏫",
  "coffee": "🔹",
  "cola": "🔹",
  "cold fruit": "🍎",
  "cold water": "🥤",
  "come back": "🙋",
  "comfortable": "🤗",
  "cone": "🍦",
  "cooked carrots": "🥕",
  "cough": "🤒",
  "count": "🔹",
  "cream cheese": "👤",
  "croissant": "🥞",
  "croutons": "🔹",
  "crunchy": "🍟",
  "cup water": "🥤",
  "dad help": "👨",
  "dance": "🎵",
  "danger": "⚠️",
  "dip": "🥫",
  "dipping sauce": "🥫",
  "driver": "🚌",
  "eat": "🍽️",
  "eggs and meat": "🍳",
  "everyone": "👥",
  "fan": "🔹",
  "fever": "🤒",
  "fidget": "🔹",
  "firefighter": "🛡️",
  "food": "🍽️",
  "foot hurts": "🤕",
  "fork": "🔹",
  "frosting": "🍪",
  "frozen fruit": "🍎",
  "frozen yogurt": "🥶",
  "fruit bar": "🍎",
  "fruit punch": "🍎",
  "fruit smoothie": "🥤",
  "gentle": "🔹",
  "girl": "👧",
  "give me": "🤲",
  "go away": "🔹",
  "go home": "🏠",
  "good afternoon": "🛑",
  "good job": "👍",
  "graham cracker": "🫓",
  "graham crackers": "🫓",
  "grape juice": "🥤",
  "great job": "🍽️",
  "grilled chicken": "🍗",
  "gummy bears": "🍬",
  "gummy worms": "🍬",
  "ham": "🔹",
  "hand hurts": "🤕",
  "hard": "😣",
  "have fun": "🔹",
  "he": "👤",
  "headphones": "📱",
  "help me breathe": "🍽️",
  "help please": "🆘",
  "hey": "👋",
  "hide": "👋",
  "home": "🏠",
  "home person": "👨‍👩‍👧",
  "hug dad": "👨",
  "hug mom": "👩",
  "hurt teeth": "🤕",
  "i am done": "✅",
  "i am happy": "😊",
  "i am here": "👤",
  "i am hurt": "🤕",
  "i am mad": "😠",
  "i am okay": "✅",
  "i am proud": "😌",
  "i am ready": "📘",
  "i am sad": "😢",
  "i am scared": "💖",
  "i am stuck": "😣",
  "i am tired": "😴",
  "i can": "💪",
  "i can't": "💪",
  "i care": "💖",
  "i did it": "🔹",
  "i didn't mean to": "🙋",
  "i don't understand": "🛑",
  "i feel good": "👍",
  "i feel happy": "😊",
  "i feel lonely": "🥺",
  "i feel mad": "😠",
  "i feel sad": "😢",
  "i feel scared": "💖",
  "i feel sick": "🤒",
  "i forgive you": "😔",
  "i go": "🔹",
  "i like that": "🔹",
  "i like you": "👉",
  "i love dad": "👨",
  "i love mom": "👩",
  "i love my family": "👨‍👩‍👧",
  "i need a break": "‼️",
  "i need bathroom": "🚽",
  "i need dad": "👨",
  "i need doctor": "🧑‍⚕️",
  "i need food": "🍽️",
  "i need friend": "👥",
  "i need help": "🆘",
  "i need medicine": "🧑‍⚕️",
  "i need mom": "👩",
  "i need nurse": "🧑‍⚕️",
  "i need quiet": "‼️",
  "i need rest": "😴",
  "i need teacher": "🧑‍🏫",
  "i need water": "🥤",
  "i tried": "🔹",
  "i want dad": "👨",
  "i want mom": "👩",
  "i want more": "✨",
  "i wanted that": "✨",
  "i worked hard": "😣",
  "ice cream sandwich": "🥪",
  "ice water": "🥤",
  "it's okay": "✅",
  "jelly": "🔹",
  "jelly sandwich": "🥪",
  "joke": "😜",
  "juice box": "🥤",
  "jump": "🔹",
  "keep going": "🔹",
  "kid": "🔹",
  "kids": "👥",
  "kind": "🔹",
  "later": "⏳",
  "laugh": "😜",
  "lid": "🔹",
  "little hug": "🤗",
  "lollipop": "🔹",
  "look": "👀",
  "love and care": "💖",
  "lunch": "🍽️",
  "lunch helper": "🍽️",
  "m and m's": "➕",
  "mandarin oranges": "🍎",
  "maybe": "🔹",
  "mcdonald's": "🍟",
  "me": "🙋",
  "mine": "🤲",
  "mixed fruit": "🍎",
  "mom help": "👩",
  "more berries": "🍎",
  "more cake": "🍪",
  "more candy": "🍬",
  "more cereal": "🥣",
  "more chicken": "🍗",
  "more chips": "🍟",
  "more cookie": "🍪",
  "more gummies": "🍬",
  "more juice": "🥤",
  "more lemonade": "🥤",
  "more milk": "🥤",
  "more please": "🙏",
  "more pudding": "➕",
  "more soda": "🥤",
  "more vegetables": "🥕",
  "more water": "🥤",
  "move": "🔹",
  "music off": "🎵",
  "my": "🙋",
  "my family": "👨‍👩‍👧",
  "my friend": "👥",
  "my friends": "👥",
  "my toy": "🎮",
  "nana": "👵",
  "nap": "😴",
  "neighbor": "👥",
  "new friend": "👥",
  "new person": "😬",
  "new place": "😬",
  "next": "🔁",
  "nice": "🥶",
  "nice work": "🥶",
  "no more": "🛑",
  "no one": "🛑",
  "no soda": "🥤",
  "no thank you": "🙏",
  "noodle soup": "🍝",
  "noodles": "🍝",
  "not close": "🫧",
  "not safe": "🛑",
  "now": "🛑",
  "office": "🥶",
  "old friend": "👥",
  "one more": "➕",
  "open": "🔹",
  "orange soda": "🥤",
  "pancake": "🍪",
  "pants": "🔹",
  "papa": "👴",
  "parent": "👨‍👩‍👧",
  "park": "🌳",
  "party": "🔹",
  "peaches cup": "🥤",
  "peanut butter sandwich": "🥪",
  "pee": "🚽",
  "pink lemonade": "🥤",
  "play friend": "👥",
  "playground": "🎮",
  "please help": "🆘",
  "please stay": "🙏",
  "police officer": "🥶",
  "poop": "🚽",
  "potato chips": "🥔",
  "pouch": "🔹",
  "privacy": "🚽",
  "protein bar": "🍫",
  "quiet room": "🫧",
  "read": "📘",
  "read with me": "📘",
  "really excited": "🤩",
  "recess": "🔹",
  "ritz": "🫓",
  "room": "🔹",
  "root beer": "🔹",
  "run": "🔹",
  "runny nose": "🛑",
  "safe hug": "🤗",
  "safe person": "🛡️",
  "safe place": "🛡️",
  "saltines": "🫓",
  "sausage": "🍳",
  "school nurse": "🧑‍🏫",
  "scrambled eggs": "🍳",
  "seat": "🍽️",
  "see you soon": "👋",
  "she": "👤",
  "show me": "👀",
  "sip": "🔹",
  "sit": "🔹",
  "sleep": "🌙",
  "slow breath": "🍽️",
  "smile": "😊",
  "snack bar": "🍫",
  "soft": "🔹",
  "soft voice": "🥶",
  "someone": "👥",
  "soup and rice": "🍲",
  "sour": "🔹",
  "spill": "🔹",
  "spoon": "🥣",
  "sprinkles": "🍪",
  "sprite": "🔹",
  "stand": "➕",
  "start": "🔹",
  "stay": "🔹",
  "strawberry ice cream": "🍦",
  "strawberry lemonade": "🥤",
  "strawberry milk": "🥤",
  "strawberry smoothie": "🥤",
  "sugar cookie": "🍪",
  "sweater": "🍽️",
  "swing": "🔹",
  "syrup": "🔹",
  "take it": "🤲",
  "talk": "🗣️",
  "tea": "🔹",
  "team": "👥",
  "tears": "😢",
  "tell me": "🙋",
  "that was good": "👍",
  "them": "👤",
  "they": "👋",
  "throw up": "🤒",
  "tissue": "🔹",
  "together": "👤",
  "toilet": "🚽",
  "too bright": "⚠️",
  "too close": "🫧",
  "tortilla chips": "🍟",
  "try": "💪",
  "try again": "🔁",
  "turkey": "🔹",
  "us": "👥",
  "vanilla ice cream": "🍦",
  "vanilla pudding": "🔹",
  "very mad": "😠",
  "visit": "🔹",
  "waffle": "🥞",
  "wait for me": "⏳",
  "wait please": "🙏",
  "wake up": "🌞",
  "walk": "🔹",
  "warm": "🥵",
  "warm cookie": "🍪",
  "warm milk": "🥤",
  "warm up": "🥵",
  "wash hands": "🚽",
  "watch": "🔹",
  "wave": "👋",
  "we": "👥",
  "wendy's": "👥",
  "what are you doing": "👉",
  "what happens": "😟",
  "where is dad": "👨",
  "where is mom": "👩",
  "white milk": "🥤",
  "wipe": "🔹",
  "with me": "🙋",
  "with mom": "👩",
  "work": "🔹",
  "wrapper": "🔹",
  "yes please": "🙏",
  "yogurt smoothie": "🥤",
  "you": "👉",
  "you are here": "👉",
  "you are nice": "🥶",
  "you did it": "👉",
  "you go": "👉",
  "you help me": "🆘",
  "you helped me": "🆘",
  "your": "👉",
  "your toy": "🎮",
  "yours": "👉",

  // V5.21 generated coverage for expanded remaining sidebar topics
  "a": "🔹",
  "a little": "🔹",
  "a lot": "🔹",
  "accident": "🔹",
  "accident words": "✏️",
  "after": "🔹",
  "after lunch": "🔹",
  "after school": "🏫",
  "afternoon": "❌",
  "aide": "🔹",
  "all": "🔹",
  "allergy": "🔹",
  "alphabet": "🔹",
  "animal": "🔹",
  "animal places": "🏠",
  "ankle": "🔹",
  "another": "❌",
  "answer": "🔹",
  "answering": "🔹",
  "apartment": "🎨",
  "app": "🔹",
  "arcade": "🔹",
  "arm": "🧍",
  "arm hurts": "🧍",
  "arms and hands": "🧍",
  "around": "🔹",
  "arrival": "🔹",
  "art": "🎨",
  "art items": "🎨",
  "art tools": "🎨",
  "ask": "🔹",
  "ask teacher": "🏫",
  "assembly": "🔹",
  "b": "🔹",
  "back": "🧍",
  "backpack": "🧍",
  "backpack items": "🧍",
  "bad": "🔹",
  "bag": "🔹",
  "ball toys": "🧸",
  "bandage": "🤕",
  "bar wrapper": "🔹",
  "baseball": "⚽",
  "basket": "🔹",
  "basketball": "⚽",
  "bat": "🔹",
  "bath": "🔹",
  "bathroom actions": "🏠",
  "bathroom health": "🏠",
  "bathroom help": "🏠",
  "bathroom items": "🏠",
  "bathroom needs": "🏠",
  "bathroom room": "🏠",
  "battery": "🔹",
  "beach": "🔹",
  "bedroom items": "🏠",
  "bedroom room": "🏠",
  "bedtime actions": "🛏️",
  "before": "🔹",
  "before after": "🔹",
  "before after when": "🕒",
  "before bed": "🛏️",
  "behind": "🔹",
  "belly": "🔹",
  "belly and back": "🧍",
  "bench": "🔹",
  "beside": "🔹",
  "bike": "🔹",
  "bin": "🔹",
  "bird": "🔹",
  "bite": "🔹",
  "bleeding": "🤕",
  "blocks": "🧸",
  "blood": "🔹",
  "blood pressure": "🔹",
  "board": "🏫",
  "board game": "🏫",
  "boat": "🔹",
  "body actions": "🧍",
  "body boundaries": "🧍",
  "body parts": "🎨",
  "bones": "🎛️",
  "book items": "📚",
  "books": "📚",
  "boots": "🔹",
  "bottom": "🔹",
  "bounce": "🔹",
  "box": "🔹",
  "break and sensory": "🤫",
  "break choices": "🤫",
  "bring it": "🔹",
  "broken": "🔹",
  "broom": "🏠",
  "bruise": "🤕",
  "brush": "🔹",
  "brush teeth": "🦷",
  "bug": "🔹",
  "build": "🔹",
  "building toys": "🧸",
  "bump": "🤕",
  "burning": "🔹",
  "bus": "🚌",
  "bus area": "🚌",
  "bus line": "🚌",
  "bus seat": "🚌",
  "bus stop": "🚌",
  "button": "🎛️",
  "c": "🔹",
  "cafeteria": "🔹",
  "calm corner": "🤫",
  "calm items": "🤫",
  "calming actions": "🤫",
  "can i": "🙋",
  "can i be done": "🙋",
  "can i choose": "🙋",
  "can i drink": "🥤",
  "can i eat": "🍽️",
  "can i go": "🚶",
  "can i have": "🙋",
  "can i help": "🆘",
  "can i play": "🙋",
  "can i rest": "🛏️",
  "can i stop": "🛡️",
  "can i use": "🙋",
  "can i use tablet": "🍽️",
  "can i watch": "🙋",
  "can questions": "❓",
  "can we": "🙋",
  "can we eat": "🍽️",
  "can we go": "🚶",
  "can we go home": "🏠",
  "can we go outside": "🌳",
  "can we play": "🙋",
  "can we read": "📚",
  "can we stop": "🛡️",
  "can we watch": "🙋",
  "can you": "🙋",
  "can you close": "🙋",
  "can you come here": "🙋",
  "can you fix it": "🙋",
  "can you get it": "🙋",
  "can you help": "🆘",
  "can you open": "🙋",
  "can you open it": "🙋",
  "can you show me": "📺",
  "can you stay": "🙋",
  "can you stop": "🛡️",
  "can you tell me": "🙋",
  "car seat": "🚗",
  "car toy": "🚗",
  "card": "🚗",
  "cards": "🚗",
  "care choices": "🚗",
  "care needs": "🚗",
  "care places": "🏠",
  "cart": "🚗",
  "cartoon": "🚗",
  "cat": "🔹",
  "catch": "🔹",
  "change": "🔄",
  "change clothes": "👕",
  "chapter book": "📚",
  "charge phone": "📞",
  "charge tablet": "🍽️",
  "charger": "🔹",
  "charging": "🔹",
  "check body": "🧍",
  "check ears": "🧍",
  "check work": "🔹",
  "checkout": "🛒",
  "cheek": "🔹",
  "chest": "🔹",
  "chew": "🔹",
  "chills": "🔹",
  "chin": "🔹",
  "chips bag": "🔹",
  "choice control": "☝️",
  "choice questions": "❓",
  "choice requests": "☝️",
  "choose": "☝️",
  "chopsticks": "🔹",
  "circle": "🔹",
  "circle time": "🕒",
  "classroom": "🏠",
  "classroom items": "🏠",
  "classroom room": "🏠",
  "classroom work": "🏠",
  "clean cut": "🤕",
  "clean up": "🧼",
  "clean words": "✏️",
  "cleaning at home": "🏠",
  "cleaning help": "🆘",
  "cleaning items": "🧼",
  "click": "🔹",
  "climb": "🔹",
  "climb down": "🔹",
  "climb up": "🔹",
  "climber": "🔹",
  "clinic": "🧑‍⚕️",
  "close app": "🎛️",
  "close book": "📚",
  "close box": "🎛️",
  "close door": "🎛️",
  "close eyes": "🧍",
  "closet": "🎛️",
  "clothes store": "🛒",
  "clothing": "🔹",
  "clothing help": "🆘",
  "cloud": "🔊",
  "coat": "🔹",
  "cold symptoms": "🔹",
  "color": "🎨",
  "color pencil": "✏️",
  "colored pencil": "✏️",
  "come": "🔹",
  "comfort for pain": "🤕",
  "communication actions": "🎛️",
  "communication needs": "🆘",
  "community places": "🏠",
  "computer": "💻",
  "container": "🎛️",
  "control actions": "🎛️",
  "controller": "🎛️",
  "copy": "🔹",
  "cord": "🔹",
  "corner": "🔹",
  "costume": "🔹",
  "couch": "🤕",
  "cracker box": "🔹",
  "crawl": "🔹",
  "crayon": "🎨",
  "cream": "🔹",
  "cross": "🔹",
  "crosswalk": "🚶",
  "cut": "🤕",
  "daily clothes": "👕",
  "daily schedule": "🕒",
  "dentist": "🦷",
  "dentist care": "🚗",
  "desk": "🏫",
  "diarrhea": "🔹",
  "dice": "🔹",
  "different": "🔄",
  "direction words": "✏️",
  "dirty": "✋",
  "dishes": "🔹",
  "dizzy": "🔹",
  "do again": "🔹",
  "doctor care": "🚗",
  "doctor kit": "🧑‍⚕️",
  "doctor office": "🧑‍⚕️",
  "doctor words": "🧑‍⚕️",
  "dog": "🔹",
  "dog park": "🌳",
  "doll": "🧸",
  "doll house": "🏠",
  "don't like": "💖",
  "don't touch": "🤕",
  "door closed": "🎛️",
  "down": "🔹",
  "draw": "🎨",
  "dress": "🔹",
  "dresser": "🔹",
  "dressing help": "🆘",
  "drink items": "🥤",
  "drink water": "🥤",
  "drive": "🚗",
  "drive car": "🚗",
  "driveway": "🚗",
  "drop": "🔹",
  "drops": "🔹",
  "dry": "🔹",
  "dry hands": "🧍",
  "ear": "🔹",
  "ears": "🧍",
  "eat drink": "🍽️",
  "eating at home": "🏠",
  "eating help": "🍽️",
  "eating items": "🍽️",
  "elbow": "🔹",
  "emergency words": "✏️",
  "empty": "🔹",
  "enough": "❌",
  "erase": "🔹",
  "eraser": "🔹",
  "eyes": "🧍",
  "face": "🧍",
  "fall": "🔹",
  "family house": "🏠",
  "family places": "🏠",
  "family who": "👥",
  "far": "🔹",
  "farm": "🧍",
  "favorite": "💖",
  "favorite book": "📚",
  "favorite items": "💖",
  "favorite toy": "🧸",
  "feeling sick": "🤒",
  "feet": "🔹",
  "field trip": "🔹",
  "find": "🔹",
  "find it": "🔹",
  "finger": "🔹",
  "finish": "🔹",
  "finished work": "✅",
  "first": "🔹",
  "first aid": "🔹",
  "first break then work": "🤫",
  "fish": "🔹",
  "fix": "🔹",
  "fix change": "🔄",
  "floor": "🔹",
  "flower": "🔹",
  "flush": "🔹",
  "folder": "✏️",
  "following directions": "🎛️",
  "food containers": "🍽️",
  "food drink needs": "🍽️",
  "foot": "🧍",
  "football": "⚽",
  "forehead": "🧍",
  "freezer": "🍽️",
  "fridge": "🍽️",
  "friend house": "🏠",
  "friend who": "👥",
  "fries": "🔹",
  "from": "🔹",
  "full": "🔹",
  "fun places": "🏠",
  "furniture": "🔹",
  "game play": "🧸",
  "game toys": "🧸",
  "garage": "🔹",
  "give it": "🔹",
  "glasses": "🔹",
  "glove": "💖",
  "gloves": "👕",
  "glue": "🔹",
  "go actions": "🚶",
  "go bathroom": "🏠",
  "go car": "🚗",
  "go doctor": "🚶",
  "go inside": "🏠",
  "go now": "🚶",
  "go outside": "🌳",
  "go play": "🚶",
  "go school": "🏫",
  "go store": "🚶",
  "go there": "🚶",
  "go to": "🚶",
  "go to bathroom": "🏠",
  "go to class": "🏫",
  "go to nurse": "🚶",
  "goal": "🚶",
  "going home": "🏠",
  "going words": "🚶",
  "grandma house": "🏠",
  "grandpa house": "🏠",
  "grass": "🌳",
  "grocery store": "🛒",
  "group": "🔹",
  "group work": "🔹",
  "gummies pack": "🔹",
  "gym": "🔹",
  "hair": "🔹",
  "hallway": "🔹",
  "hand": "🧍",
  "hat": "👕",
  "hate": "👕",
  "head": "🧍",
  "head and face": "🧍",
  "health actions": "🎛️",
  "healthy": "🔹",
  "heart": "🎨",
  "heavy work": "🔹",
  "helmet": "🛡️",
  "help": "🆘",
  "help actions": "🆘",
  "help me dress": "🆘",
  "help requests": "🆘",
  "help with work": "🆘",
  "helper teacher": "🏫",
  "helper who": "🆘",
  "here": "🔹",
  "highlighter": "💡",
  "hold on": "🎛️",
  "home actions": "🏠",
  "home items": "🏠",
  "home needs": "🏠",
  "home places": "🏠",
  "hoodie": "🔹",
  "hospital": "🧑‍⚕️",
  "house": "🏠",
  "how": "🛠️",
  "how are": "🛠️",
  "how can": "🛠️",
  "how did": "🛠️",
  "how do": "🛠️",
  "how do i": "🛠️",
  "how do i feel": "🛠️",
  "how do you feel": "🛠️",
  "how feel": "🛠️",
  "how help": "🆘",
  "how is": "🛠️",
  "how long": "🛠️",
  "how many": "🛠️",
  "how much": "🛠️",
  "how phrases": "🛠️",
  "how questions": "❓",
  "how to": "🛠️",
  "hug toy": "🧸",
  "hurt ears": "🧍",
  "hurt eyes": "🧍",
  "i am sick": "🤒",
  "i don't know": "❌",
  "i don't like": "💖",
  "i feel": "🔹",
  "i know": "❌",
  "i like": "💖",
  "i need": "🆘",
  "i need book": "📚",
  "i need headphones": "🤫",
  "i need paper": "✏️",
  "i need pencil": "✏️",
  "i need tablet": "🍽️",
  "i tell you": "🔹",
  "i want": "🔹",
  "ice pack": "🤕",
  "in": "🔹",
  "in front": "🎛️",
  "inhaler": "🔹",
  "injury": "🔹",
  "inside home": "🏠",
  "ipad": "💻",
  "itchy": "✋",
  "jacket": "👕",
  "keyboard": "🏫",
  "kick": "🔹",
  "kitchen": "🍽️",
  "kitchen items": "🍽️",
  "kitchen room": "🏠",
  "kitchen toy": "🍽️",
  "knee": "🔹",
  "kneel": "🔹",
  "knife": "🔹",
  "lake": "🔹",
  "lamp": "💡",
  "last": "🔹",
  "laundry": "🔹",
  "lay down": "🔹",
  "leaf": "🔹",
  "leave": "🔹",
  "leaving words": "✏️",
  "left": "🔹",
  "leg": "🧍",
  "leg hurts": "🧍",
  "legos": "🚶",
  "legs and feet": "🧍",
  "less": "🔹",
  "letter": "✏️",
  "letters": "✏️",
  "library": "📚",
  "library book": "📚",
  "lift": "🔹",
  "light doors": "💡",
  "lights off": "💡",
  "lights on": "💡",
  "like don't like": "💖",
  "line": "🔹",
  "line up": "🔹",
  "lips": "🔹",
  "liquid medicine": "🧑‍⚕️",
  "listen heart": "🎨",
  "listening actions": "🎛️",
  "living room": "🏠",
  "lose": "🔹",
  "lost": "🔹",
  "loud music": "🎵",
  "loud voice": "🔊",
  "lunch box": "🔹",
  "lunch room": "🏠",
  "magnet tiles": "🔹",
  "main teacher": "🏫",
  "make": "🔹",
  "make food": "🍽️",
  "march": "🔹",
  "marker": "🎨",
  "match": "🔹",
  "matching": "🔹",
  "math": "🔹",
  "meal tools": "🍽️",
  "medical places": "🏠",
  "medical safety": "🧑‍⚕️",
  "medicine and care": "🚗",
  "menu": "🔹",
  "message": "📞",
  "messy": "🔹",
  "middle": "🔹",
  "milk carton": "🚗",
  "mirror": "🔹",
  "mix": "🔹",
  "more blocks": "🧸",
  "more done": "➕",
  "more less": "➕",
  "more show": "📺",
  "more work": "➕",
  "morning": "🔹",
  "morning work": "🔹",
  "mouse": "💻",
  "mouth": "🧍",
  "mouth and teeth": "🦷",
  "movement": "🚶",
  "movement tools": "🚶",
  "movie": "📺",
  "muscles": "🔹",
  "museum": "🔹",
  "music on": "🎵",
  "my body": "🧍",
  "my name": "🔹",
  "name": "🔹",
  "napkin": "🛏️",
  "nature things": "🌳",
  "nauseous": "🤒",
  "near": "🔹",
  "need quiet": "🤫",
  "next to": "🔹",
  "night": "🔹",
  "night light": "💡",
  "nose": "🧍",
  "not again": "❌",
  "not enough": "❌",
  "not favorite": "❌",
  "not here": "❌",
  "not that": "👕",
  "not yet": "❌",
  "notebook": "📚",
  "nuggets": "🔹",
  "number": "🔹",
  "numbers": "🔹",
  "nurse office": "🧑‍⚕️",
  "occupational therapist": "🍽️",
  "occupational therapy": "🍽️",
  "off": "🎛️",
  "ointment": "🔹",
  "on": "🎛️",
  "on off": "🎛️",
  "one": "🎛️",
  "one more minute": "➕",
  "open app": "🎛️",
  "open book": "📚",
  "open box": "🎛️",
  "open close": "🎛️",
  "open door": "🎛️",
  "open mouth": "🧍",
  "other one": "🎛️",
  "ouch": "🤕",
  "out": "🔹",
  "outlet": "🔹",
  "outside places": "🏠",
  "outside play": "🌳",
  "outside safety": "🌳",
  "outside things": "🌳",
  "over": "🔹",
  "pack up": "🔹",
  "page": "📚",
  "pain and hurt": "🤕",
  "pain location": "🤕",
  "pain needs": "🆘",
  "pain type": "🤕",
  "paint": "🎨",
  "pajamas": "👕",
  "paper": "✏️",
  "paper items": "✏️",
  "paper tools": "✏️",
  "parking": "🌳",
  "parking lot": "🌳",
  "partner": "🎨",
  "path": "🔹",
  "pause": "🔹",
  "pause game": "🧸",
  "pen": "🔹",
  "pencil": "✏️",
  "people who": "👥",
  "permission": "🙋",
  "pet store": "🛒",
  "pharmacy": "🧍",
  "phone": "📞",
  "physical therapist": "🔹",
  "physical therapy": "🧑‍⚕️",
  "pick": "☝️",
  "pick up": "☝️",
  "picnic": "🔹",
  "picture": "🔹",
  "picture book": "📚",
  "pieces": "🔹",
  "pill": "🔹",
  "pillow": "🛏️",
  "place words": "🏠",
  "plane": "🔹",
  "plate": "🍽️",
  "play actions": "🎛️",
  "play food": "🍽️",
  "play game": "🧸",
  "play place": "🏠",
  "play room": "🏠",
  "playground helper": "🌳",
  "playground outside": "🌳",
  "playground things": "🌳",
  "playing at home": "🏠",
  "plug": "🔹",
  "plush": "🔹",
  "point": "🔹",
  "pool": "🔹",
  "porch": "🔹",
  "position words": "✏️",
  "potty": "🚽",
  "pour": "🔹",
  "pretend": "🎮",
  "pretend play": "🎮",
  "pretend toys": "🧸",
  "privacy words": "🚽",
  "pull": "🔹",
  "pull down": "🔹",
  "pull up": "🔹",
  "puppet": "🔹",
  "push": "🔹",
  "put away": "🔹",
  "put down": "🔹",
  "put in": "🔹",
  "put on": "🎛️",
  "put on pajamas": "👕",
  "put on shoes": "👕",
  "puzzle": "🧸",
  "question": "❓",
  "question helpers": "🆘",
  "quiet break": "🤫",
  "quiet music": "🤫",
  "quiet places": "🏠",
  "quiet tools": "🤫",
  "quiet voice": "🤫",
  "race car": "🚗",
  "rain": "🔹",
  "raincoat": "🔹",
  "raise hand": "🧍",
  "read again": "📚",
  "read book": "📚",
  "reading": "📚",
  "reading actions": "📚",
  "reading and writing": "📚",
  "repeat": "🍽️",
  "rest needs": "🛏️",
  "restaurant": "🛏️",
  "restaurants": "🛏️",
  "resting at home": "🏠",
  "return to work": "🎮",
  "ride": "🔹",
  "right": "🔹",
  "rock": "🔹",
  "roll": "🔹",
  "room places": "🏠",
  "routine when": "🕒",
  "rug": "🔹",
  "rule": "🔹",
  "safe people": "🛡️",
  "safety actions": "🛡️",
  "safety health": "🛡️",
  "safety items": "🛡️",
  "safety needs": "🆘",
  "safety place words": "🏠",
  "safety things": "🛡️",
  "same": "🔁",
  "same different": "🔁",
  "sandals": "🔹",
  "sandbox": "🔹",
  "say": "🔹",
  "say again": "🔹",
  "scale": "🔹",
  "schedule": "🕒",
  "schedule when": "🕒",
  "school actions": "🏫",
  "school bus": "🏫",
  "school clothes": "🏫",
  "school events": "🏫",
  "school items": "🏫",
  "school needs": "🏫",
  "school office": "🏫",
  "school places": "🏠",
  "school tools": "🏫",
  "school who": "🏫",
  "scissors": "🔹",
  "scoop": "🔹",
  "scooter": "🔹",
  "scratch": "🤕",
  "scratchy": "🤕",
  "screen": "💻",
  "seat belt": "🍽️",
  "secretary": "🔹",
  "seesaw": "🔹",
  "self care actions": "🚗",
  "sensory body": "🤫",
  "sensory items": "🤫",
  "sensory needs": "🤫",
  "sensory tools": "🤫",
  "sensory toy": "🤫",
  "sentence": "🔹",
  "shade": "🔹",
  "sharp pain": "🤕",
  "sharpener": "🔹",
  "shelf": "🔹",
  "shirt": "👕",
  "shoes": "👕",
  "shorts": "🔹",
  "shot": "🔹",
  "shoulder": "🔹",
  "show": "📺",
  "show again": "📺",
  "show hurt": "📺",
  "show you": "📺",
  "shower": "📺",
  "sick words": "✏️",
  "side": "🔹",
  "sidewalk": "🚶",
  "sink": "🚽",
  "sit stand": "🔹",
  "skin": "🔹",
  "skip": "🔹",
  "skirt": "🔹",
  "sleep clothes": "🛏️",
  "sleep items": "🛏️",
  "sleep rest": "🛏️",
  "slide": "🔹",
  "slippers": "🔹",
  "slow down": "🔹",
  "smooth": "🔹",
  "snack items": "🍽️",
  "sneakers": "🔹",
  "sneeze": "🤒",
  "snow": "❌",
  "soap": "🧼",
  "soccer ball": "⚽",
  "social needs": "🆘",
  "socks": "👕",
  "soft comfort": "🔹",
  "soft toy": "🧸",
  "soft toys": "🧸",
  "some": "🔹",
  "song": "🎵",
  "soon": "🕒",
  "sore": "🔹",
  "sort": "🔹",
  "sorting": "🔹",
  "sound": "🔊",
  "sound out": "🔊",
  "speak": "🔹",
  "speaker": "🎵",
  "specials": "🔹",
  "speech": "🚽",
  "spell": "🔹",
  "spin": "🔹",
  "spinner": "🔹",
  "splash pad": "🔹",
  "sports things": "🔹",
  "squishy": "🔹",
  "stack": "🔹",
  "stairs": "🔹",
  "start game": "🎨",
  "start stop": "🎨",
  "stay home": "🏠",
  "step": "🔹",
  "stick": "🔹",
  "stickers": "🔹",
  "sticky": "✋",
  "stinging": "🔹",
  "stomach": "🧍",
  "stomach sick": "🧍",
  "stool": "🔹",
  "stop actions": "🛡️",
  "stop car": "🚗",
  "stop safety": "🛡️",
  "stop sound": "🛡️",
  "store": "🛒",
  "stores": "🛒",
  "story": "📚",
  "story words": "📚",
  "street": "🌳",
  "stretch": "🔹",
  "stroller": "🔹",
  "stuffed animal": "🧸",
  "stuffy nose": "🧍",
  "substitute teacher": "🏫",
  "sun": "🔹",
  "sunglasses": "🔹",
  "sunscreen": "💻",
  "swallow": "🔹",
  "sweaty": "🍽️",
  "swim": "🔹",
  "swipe": "🧼",
  "switch": "🔹",
  "table": "🍽️",
  "table work": "🍽️",
  "tablet game": "🍽️",
  "tablet play": "🍽️",
  "take medicine": "🧑‍⚕️",
  "take off": "🎛️",
  "take off shoes": "👕",
  "take out": "🔹",
  "tap": "🔹",
  "taste": "🔹",
  "taste texture": "🔹",
  "teach me": "🔹",
  "technology": "💻",
  "teddy bear": "🧸",
  "teeth": "🦷",
  "teeth hurt": "🦷",
  "tell": "🔹",
  "tell doctor": "🧑‍⚕️",
  "that": "👕",
  "that one": "👕",
  "that place": "🏠",
  "therapy": "🧑‍⚕️",
  "therapy care": "🚗",
  "there": "🔹",
  "thermometer": "👨‍👩‍👧",
  "this": "☝️",
  "this one": "☝️",
  "this place": "🏠",
  "this that": "👕",
  "three": "🔹",
  "throat": "🔹",
  "throat hurts": "🤕",
  "through": "🔹",
  "throw": "🔹",
  "throw away": "🔹",
  "thumb": "🔹",
  "tie": "🔹",
  "tie shoes": "👕",
  "time words": "✏️",
  "timer": "🕒",
  "today": "🔹",
  "toe": "🔹",
  "toilet words": "🚽",
  "tomorrow": "🔹",
  "tongue": "🎛️",
  "too fast": "🔹",
  "too hard": "🔹",
  "too long": "🎛️",
  "too much body": "🧍",
  "too much touch": "🤕",
  "too spicy": "🔹",
  "too tight": "🔹",
  "tool needs": "🆘",
  "tools": "🔹",
  "tooth": "🦷",
  "tooth hurts": "🦷",
  "toothbrush": "🦷",
  "toothpaste": "🦷",
  "top": "🔹",
  "touch": "🤕",
  "towel": "🧼",
  "tower": "🔹",
  "toy phone": "🧸",
  "toy play": "🧸",
  "toy store": "🛒",
  "toys": "🧸",
  "trace": "🔹",
  "track": "🔹",
  "tractor": "🔹",
  "train": "🔹",
  "transition": "🎛️",
  "transition actions": "🎛️",
  "transitions": "🎛️",
  "trash": "🔹",
  "trash can": "🔹",
  "travel actions": "🚶",
  "travel needs": "🚶",
  "travel places": "🏠",
  "tray": "🔹",
  "tree": "🌳",
  "trip": "🔹",
  "trips": "🔹",
  "truck": "🔹",
  "tub": "🔹",
  "turn in": "🎮",
  "turn off": "🎛️",
  "turn off light": "💡",
  "turn on": "🎛️",
  "turn on light": "💡",
  "turn page": "📚",
  "turn taking": "🎮",
  "tv": "📺",
  "tv off": "📺",
  "tv on": "📺",
  "two": "🔹",
  "type": "🔹",
  "umbrella": "🔹",
  "under": "🔹",
  "underwear": "🔹",
  "undress": "🔹",
  "up": "🔹",
  "up down": "🔹",
  "use": "🔹",
  "use button": "🎛️",
  "use words": "✏️",
  "utensils": "🔹",
  "vacuum": "🔹",
  "vehicle things": "🚗",
  "vehicle toys": "🚗",
  "velcro": "🔹",
  "video": "🔹",
  "video call": "📞",
  "vitamin": "🔹",
  "voice": "🔹",
  "volume": "🔊",
  "volume down": "🔊",
  "volume up": "🔊",
  "wagon": "🚶",
  "wait outside": "🌳",
  "waiting": "🕒",
  "waiting when": "🕒",
  "walk break": "🚶",
  "walk run": "🚶",
  "walking": "🚶",
  "wash": "🧼",
  "wash clean": "🧼",
  "water bottle": "🥤",
  "water places": "🏠",
  "weak": "🔹",
  "weather clothes": "🍽️",
  "weather things": "🍽️",
  "weighted blanket": "🛏️",
  "wet": "✋",
  "what": "👕",
  "what activity": "👕",
  "what are": "👕",
  "what are we doing": "👕",
  "what book": "📚",
  "what breakfast": "🤫",
  "what changed": "👕",
  "what chips": "👕",
  "what class": "🏫",
  "what color": "🎨",
  "what did": "👕",
  "what did i do": "👕",
  "what did you do": "👕",
  "what dinner": "👕",
  "what do": "👕",
  "what do i feel": "👕",
  "what do i need": "🆘",
  "what do you feel": "👕",
  "what do you have": "👕",
  "what drink": "🥤",
  "what else": "👕",
  "what feeling": "👕",
  "what food": "🍽️",
  "what fruit": "👕",
  "what game": "🧸",
  "what gummies": "👕",
  "what happened": "👕",
  "what hurts": "👕",
  "what is": "👕",
  "what is it": "👕",
  "what is that": "👕",
  "what is wrong": "👕",
  "what kind": "👕",
  "what lunch": "👕",
  "what next": "👕",
  "what now": "👕",
  "what object": "👕",
  "what phrases": "👕",
  "what play": "👕",
  "what questions": "👕",
  "what size": "👕",
  "what snack": "🍽️",
  "what toy": "🧸",
  "what work": "👕",
  "when are": "🕒",
  "when bath": "🕒",
  "when bathroom": "🏠",
  "when bed": "🛏️",
  "when bus": "🚌",
  "when can": "🕒",
  "when car": "🚗",
  "when dad": "🕒",
  "when did": "🕒",
  "when do": "🕒",
  "when done": "🕒",
  "when drink": "🥤",
  "when eat": "🍽️",
  "when finished": "🕒",
  "when go home": "🏠",
  "when home": "🏠",
  "when is": "🕒",
  "when is break": "🕒",
  "when is lunch": "🕒",
  "when mom": "🕒",
  "when next": "🕒",
  "when now": "🕒",
  "when outside": "🌳",
  "when phrases": "🕒",
  "when play": "🕒",
  "when questions": "🕒",
  "when school": "🏫",
  "when sleep": "🛏️",
  "when therapy": "🧑‍⚕️",
  "when work": "🕒",
  "where": "📍",
  "where are": "📍",
  "where are we": "📍",
  "where are we going": "🚶",
  "where body": "🧍",
  "where did": "📍",
  "where do": "📍",
  "where else": "📍",
  "where going": "🚶",
  "where hurts": "🤕",
  "where is": "📍",
  "where is backpack": "🧍",
  "where is blanket": "🛏️",
  "where is book": "📚",
  "where is cup": "🍽️",
  "where is friend": "📍",
  "where is helper": "🆘",
  "where is it": "📍",
  "where is nurse": "🧑‍⚕️",
  "where is pain": "🤕",
  "where is tablet": "🍽️",
  "where is teacher": "🏫",
  "where is toy": "🧸",
  "where next": "📍",
  "where now": "📍",
  "where object": "📍",
  "where person": "📍",
  "where phrases": "📍",
  "where place": "🏠",
  "where questions": "❓",
  "where to": "📍",
  "where to go": "🚶",
  "where words": "✏️",
  "which one": "☝️",
  "who": "👥",
  "who can": "👥",
  "who can help": "🆘",
  "who did": "👥",
  "who did it": "👥",
  "who do i ask": "👥",
  "who goes": "🚶",
  "who goes first": "🚶",
  "who has": "👥",
  "who has toy": "🧸",
  "who helps": "🆘",
  "who is": "👥",
  "who is absent": "👥",
  "who is coming": "👥",
  "who is doctor": "🧑‍⚕️",
  "who is friend": "👥",
  "who is helper": "🆘",
  "who is here": "👥",
  "who is home": "🏠",
  "who is it": "👥",
  "who is next": "👥",
  "who is nurse": "🧑‍⚕️",
  "who is safe": "🛡️",
  "who is teacher": "🏫",
  "who is that": "👕",
  "who is there": "👥",
  "who is with me": "👥",
  "who needs": "🆘",
  "who phrases": "👥",
  "who questions": "👥",
  "who wants": "👥",
  "who wants to play": "👥",
  "whole body": "🧍",
  "why": "🤔",
  "why are": "🤔",
  "why bath": "🤔",
  "why can": "🤔",
  "why can't i": "🤔",
  "why change": "🤔",
  "why clean": "🤔",
  "why crying": "🤔",
  "why did": "🤔",
  "why different": "🤔",
  "why do": "🤔",
  "why do i have to": "🤔",
  "why doctor": "🧑‍⚕️",
  "why feelings": "🤔",
  "why help": "🆘",
  "why hurt": "🤕",
  "why is": "🤔",
  "why later": "🤔",
  "why mad": "🤔",
  "why medicine": "🧑‍⚕️",
  "why no": "🤔",
  "why not": "🤔",
  "why now": "🤔",
  "why phrases": "🤔",
  "why questions": "❓",
  "why rules": "🤔",
  "why sad": "🤔",
  "why scared": "🚗",
  "why school": "🏫",
  "why stop": "🛡️",
  "why tired": "🤔",
  "why wait": "🕒",
  "why work": "🤔",
  "wiggle": "🔹",
  "win": "🔹",
  "wind": "🔹",
  "window": "🔹",
  "wipe face": "🧍",
  "wipe table": "🍽️",
  "word": "✏️",
  "work actions": "🎛️",
  "work choices": "☝️",
  "work needs": "🆘",
  "worksheet": "🔹",
  "wrist": "🔹",
  "write": "✏️",
  "writing": "🔹",
  "writing actions": "🎛️",
  "writing items": "🔹",
  "writing tools": "🔹",
  "wrong": "🎛️",
  "yard": "🌳",
  "yard outside": "🌳",
  "yes no": "✅",
  "youtube": "🔹",
  "yucky": "🚫",
  "zip": "🔹",
  "zipper": "🔹",
  "zoo": "🔹",

  "i": "🙋", "want": "✨", "need": "‼️", "feel": "❤️", "am": "🔗", "can": "💪", "don't": "🚫", "like": "👍", "have": "🖐️", "see": "👀", "hear": "👂", "think": "🧠", "go": "➡️", "stop": "🛑", "get": "🫴", "do": "✅", "and": "➕", "because": "↪️", "but": "↔️", "to": "➡️", "with": "🤝", "then": "⏭️", "when": "🕒", "if": "❔", "so": "➡️", "yes": "✅"
};

function normalize(word = "") {
  return String(word)
    .toLowerCase()
    .replace(/&/g, " and ")
    .replace(/[^\w\s']/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

const AGE_RESPECTFUL_SYMBOLS = {
  "relationships": "👥", "people": "👥", "family": "👪", "friends": "🤝",
  "feelings": "🙂", "happy": "🙂", "sad": "☹️", "mad": "😠", "scared": "😟",
  "things": "🧰", "toy": "🎯", "play": "🎮", "school": "🎓", "work": "💼",
  "body and health": "⚕️", "doctor": "⚕️", "medicine": "💊", "pain": "⚡",
  "food and drink": "🍽️", "food": "🍽️", "drink": "🥤", "places": "📍",
  "privacy": "🔒", "relationship": "🤝", "opinion": "💬", "question": "❓",
  "communication repair": "🛠️", "wrong word": "🛠️", "give me time": "⏳",
  "i know but can't say it": "💭", "technology": "💻", "transportation": "🚙"
};

// This is a sign-supported visual cue set, not a clinical ASL dictionary.
// The text label remains authoritative and unavailable signs fall back safely.
const SIGN_LANGUAGE_HAND_SYMBOLS = {
  "i": "☝️", "me": "👈", "my": "👈", "you": "👉", "we": "🤝",
  "want": "🤲", "need": "🤲", "help": "🫶", "stop": "✋",
  "yes": "👍", "no": "👎", "more": "🤲", "like": "👍", "love": "🤟",
  "finished": "🙌", "all done": "🙌", "please": "🙏", "thank you": "🙏",
  "hello": "👋", "hi": "👋", "bye": "👋", "wait": "✋", "go": "👉",
  "come": "🫴", "get": "🫴", "have": "🤲", "give": "🫴", "take": "🤲",
  "look": "👀", "see": "👀", "hear": "👂", "think": "🤔", "feel": "🫶",
  "eat": "🤌", "drink": "🤲", "bathroom": "🤟", "break": "✋",
  "mom": "👩", "dad": "👨", "teacher": "🧑‍🏫", "friend": "🤝",
  "this": "👇", "that": "👉", "where": "🤷", "what": "🤷", "who": "🤷",
  "why": "🤷", "how": "🤷", "to": "👉", "with": "🤝", "again": "🔁"
};

function emojiFor(word = "", mode = "classic") {
  const key = normalize(word);
  if (mode === "sign_language") return SIGN_LANGUAGE_HAND_SYMBOLS[key] || "🤟";
  if (mode === "age_respectful") return AGE_RESPECTFUL_SYMBOLS[key] || SYMBOLS[key] || "◆";
  return SYMBOLS[key] || "⭐";
}

function symbolSlug(word = "") {
  return normalize(word)
    .replace(/'/g, "-")
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "");
}

export default function SymbolImage({ word, profile }) {
  const mode = getSymbolDisplayMode(profile);
  const [assetFailed, setAssetFailed] = useState(false);
  const slug = symbolSlug(word);
  const useClassicAsset = mode === "classic" && slug && !assetFailed;
  const symbol = emojiFor(word, mode);

  return (
    <div className={`approvedSymbol approvedSymbol-${mode}`} data-symbol-mode={mode} aria-hidden="true">
      {useClassicAsset ? (
        <img
          className="symbolImage"
          src={`/symbols/aac/${slug}.svg`}
          alt=""
          onError={() => setAssetFailed(true)}
        />
      ) : (
        <span className="fallbackSymbol" style={{ fontSize: "2rem", lineHeight: 1 }}>{symbol}</span>
      )}
      {mode === "sign_language" && <small className="approvedSignCue">SIGN</small>}
    </div>
  );
}
