import React from "react";

const SYMBOLS = {
  "relationships": "👨‍👩‍👧", "people": "👥", "love care": "💖", "greeting": "👋", "social words": "💬", "family": "👨‍👩‍👧", "friends": "🧑‍🤝‍🧑", "help comfort": "🤗", "feelings together": "❤️", "school people": "🧑‍🏫",
  "feelings": "😊", "happy feelings": "😊", "sad feelings": "😢", "mad feelings": "😠", "scared feelings": "😨", "body feelings": "🤕", "energy": "⚡", "calm": "😌", "social feelings": "🫶", "needs with feelings": "🆘",
  "food and drink": "🍎", "fruit": "🍎", "produce": "🥕", "snacks": "🍪", "meals": "🍽️", "breakfast": "🥣", "fast food": "🍟", "drinks": "🥤", "sweets": "🍬", "hot food": "🍲", "cold food": "🧊",
  "mcdonalds": "🍟", "burger king": "🍔", "wendys": "🍔", "chick fil a": "🍗", "taco bell": "🌮", "pizza chains": "🍕", "subway": "🥪", "kfc": "🍗", "popeyes": "🍗", "sonic": "🥤", "dairy queen": "🍦", "fast food favorites": "⭐",
  "places": "🏠", "school": "🏫", "actions": "🏃", "things": "🧸", "body and health": "🩺", "questions": "❓", "recents": "🕘", "favorites": "⭐", "search": "🔎", "emergency": "🚨",

  "mom": "👩", "dad": "👨", "grandma": "👵", "grandpa": "👴", "brother": "👦", "sister": "👧", "aunt": "👩", "uncle": "👨", "cousin": "🧒", "baby": "👶", "teacher": "🧑‍🏫", "doctor": "🧑‍⚕️", "nurse": "🧑‍⚕️", "friend": "🧑", "classmate": "🧑", "helper": "🤝", "principal": "🏫", "bus driver": "🚌", "therapist": "🧑‍⚕️", "speech teacher": "🗣️", "student": "🧒",
  "i love you": "💖", "love": "💖", "hug": "🤗", "can i have a hug": "🤗", "kiss": "😘", "hold hand": "🤝", "stay with me": "🫶", "sit with me": "🪑", "help me": "🆘", "i miss you": "💭", "i need you": "🫶", "thank you": "🙏", "please": "🙂", "hi": "👋", "hello": "👋", "bye": "👋", "good morning": "🌞", "good night": "🌙", "see you later": "👋", "how are you": "❓", "i'm okay": "👌", "you're welcome": "🙂", "i'm sorry": "😔", "sorry": "😔", "excuse me": "🙋", "nice to see you": "😊", "come here": "👋", "look at me": "👀", "listen": "👂", "my turn": "☝️", "your turn": "👉", "share": "🤲", "play with me": "🛝", "talk to me": "🗣️", "i need space": "🫧", "stop please": "🛑", "again": "🔁", "more": "➕", "all done": "✅", "finished": "✅",

  "happy": "😊", "excited": "🤩", "proud": "😌", "silly": "😜", "funny": "😂", "good": "👍", "great": "🌟", "safe": "🛡️", "okay": "👌", "i like it": "👍", "i love it": "💖", "fun": "🎉", "sad": "😢", "lonely": "🥺", "miss you": "💭", "cry": "😭", "upset": "☹️", "disappointed": "😞", "not okay": "☹️", "hurt feelings": "💔", "i need hug": "🤗", "mad": "😠", "angry": "😡", "frustrated": "😣", "too much": "⚠️", "no": "❌", "i don't want": "🚫", "i need break": "⏸️", "quiet": "🤫", "wait": "⏳", "not fair": "⚖️", "scared": "😨", "worried": "😟", "nervous": "😬", "afraid": "😨", "unsafe": "⚠️", "too loud": "🔊", "dark": "🌑", "hurt": "🤕",
  "sick": "🤒", "tired": "😴", "hungry": "🍽️", "thirsty": "🥤", "hot": "🥵", "cold": "🥶", "pain": "⚡", "head hurts": "🤕", "stomach hurts": "🤢", "ear hurts": "👂", "mouth hurts": "👄", "bathroom": "🚽", "medicine": "💊", "rest": "🛏️", "water": "💧", "sleepy": "😴", "awake": "☀️", "wiggly": "🌀", "busy": "🐝", "fast": "⚡", "slow": "🐢", "break": "⏸️", "play": "🎮", "outside": "🌳", "inside": "🏠", "space": "🫧", "breathe": "🌬️", "blanket": "🛏️", "dark room": "🌑", "music": "🎵", "embarrassed": "😳", "shy": "🫣",

  "apple": "🍎", "banana": "🍌", "orange": "🍊", "grapes": "🍇", "strawberry": "🍓", "blueberry": "🫐", "watermelon": "🍉", "pineapple": "🍍", "peach": "🍑", "pear": "🍐", "mango": "🥭", "raspberry": "🍓", "blackberry": "🫐", "cherry": "🍒", "fruit cup": "🍎", "applesauce": "🥣", "raisins": "🍇",
  "carrot": "🥕", "corn": "🌽", "peas": "🟢", "green beans": "🫘", "broccoli": "🥦", "potato": "🥔", "sweet potato": "🍠", "cucumber": "🥒", "tomato": "🍅", "lettuce": "🥬", "salad": "🥗", "pickle": "🥒", "avocado": "🥑", "celery": "🥬", "vegetables": "🥦",
  "chips": "🍟", "gummies": "🍬", "fruit snacks": "🍬", "crackers": "🫓", "cookies": "🍪", "cookie": "🍪", "pretzels": "🥨", "popcorn": "🍿", "granola bar": "🍫", "cheese stick": "🧀", "yogurt": "🥣", "pudding": "🍮", "goldfish": "🐟", "trail mix": "🥜", "cereal bar": "🍫", "rice cake": "🍘", "snack": "🍪",
  "chicken nuggets": "🍗", "french fries": "🍟", "pizza": "🍕", "sandwich": "🥪", "mac and cheese": "🧀", "hot dog": "🌭", "hamburger": "🍔", "cheeseburger": "🍔", "pasta": "🍝", "spaghetti": "🍝", "rice": "🍚", "chicken": "🍗", "soup": "🍲", "tacos": "🌮", "taco": "🌮", "quesadilla": "🌮", "grilled cheese": "🥪", "meatballs": "🍝", "dinner": "🍽️", "chicken sandwich": "🥪", "milkshake": "🥤", "ice cream": "🍦", "apple slices": "🍎", "soda": "🥤", "lemonade": "🍋", "ketchup": "🍅", "sauce": "🥫", "kids meal": "🍽️",
  "cereal": "🥣", "oatmeal": "🥣", "pancakes": "🥞", "waffles": "🧇", "eggs": "🍳", "toast": "🍞", "bagel": "🥯", "muffin": "🧁", "milk": "🥛", "juice": "🧃", "breakfast bar": "🍫", "donut": "🍩", "hash browns": "🥔", "bacon": "🥓",
  "drink": "🥤", "apple juice": "🧃", "orange juice": "🧃", "chocolate milk": "🥛", "smoothie": "🥤", "sports drink": "🥤", "hot chocolate": "☕", "straw": "🥤", "cup": "🥤", "more drink": "🥤", "ice": "🧊", "candy": "🍬", "cake": "🍰", "cupcake": "🧁", "brownie": "🍫", "popsicle": "🍧", "chocolate": "🍫", "marshmallow": "🍬", "sweet": "🍬", "treat": "🍬", "too hot": "🥵", "cool down": "🌬️", "too cold": "🥶", "cold pizza": "🍕",

  "toy": "🧸", "tablet": "📱", "book": "📘", "ball": "⚽", "chair": "🪑", "bed": "🛏️", "door": "🚪", "light": "💡", "remote": "🎛️", "game": "🎮",
  "happy meal": "🍱",
  "mcflurry": "🍦",
  "ice cream cone": "🍦",
  "breakfast sandwich": "🥪",
  "whopper": "🍔",
  "onion rings": "🧅",
  "apple bites": "🍎",
  "frosty": "🍦",
  "waffle fries": "🍟",
  "chick fil a sauce": "🥫",
  "grilled nuggets": "🍗",
  "soft taco": "🌮",
  "crunchy taco": "🌮",
  "burrito": "🌯",
  "nachos": "🧀",
  "beans": "🫘",
  "beef": "🥩",
  "cheese pizza": "🍕",
  "pepperoni pizza": "🍕",
  "sausage pizza": "🍕",
  "breadsticks": "🥖",
  "cheesy bread": "🧀",
  "wings": "🍗",
  "slice": "🍕",
  "whole pizza": "🍕",
  "more pizza": "🍕",
  "turkey sandwich": "🥪",
  "ham sandwich": "🥪",
  "meatball sub": "🥪",
  "fried chicken": "🍗",
  "chicken tenders": "🍗",
  "mashed potatoes": "🥔",
  "biscuit": "🥐",
  "coleslaw": "🥗",
  "red beans and rice": "🫘",
  "corn dog": "🌭",
  "tater tots": "🥔",
  "slush": "🥤",
  "pretzel": "🥨",
  "chicken strips": "🍗",
  "blizzard": "🍦",
  "sundae": "🍨",
  "dilly bar": "🍦",
  "pretzel sticks": "🥨",

  "family people": "👨‍👩‍👧",
  "friend people": "🧑‍🤝‍🧑",
  "helper people": "🤝",
  "pronouns": "🙋",
  "groups": "👥",
  "love words": "💖",
  "hugs": "🤗",
  "kind words": "🙂",
  "missing someone": "💭",
  "care actions": "🫶",
  "praise": "👏",
  "greetings": "👋",
  "hello": "👋",
  "goodbye": "👋",
  "daily greetings": "🌞",
  "conversation starters": "💬",
  "polite words": "🙏",
  "turns": "🔁",
  "sharing": "🤲",
  "play words": "🎮",
  "space words": "🫧",
  "repair words": "🛠️",
  "conversation control": "🎛️",
  "parents": "👨‍👩‍👧",
  "grandparents": "👵",
  "siblings": "👦",
  "home family": "🏠",
  "family feelings": "❤️",
  "family actions": "🫶",
  "friend names": "🧑",
  "play together": "🛝",
  "school friends": "🏫",
  "sharing with friends": "🤲",
  "friend feelings": "❤️",
  "helpers": "🤝",
  "at home helpers": "🏠",
  "at school helpers": "🏫",
  "medical helpers": "🩺",
  "safety helpers": "🛡️",
  "ask for help": "🆘",
  "comfort": "🤗",
  "comfort people": "👥",
  "comfort actions": "🤗",
  "comfort items": "🧸",
  "comfort places": "🏠",
  "comfort words": "💬",
  "happy together": "😊",
  "sad together": "😢",
  "mad together": "😠",
  "scared together": "😨",
  "repair together": "🛠️",
  "teachers": "🧑‍🏫",
  "classmates": "👥",
  "school helpers": "🤝",
  "bus people": "🚌",
  "therapy people": "🗣️",
  "happy": "😊",
  "excited": "🤩",
  "proud": "😌",
  "silly": "😜",
  "good": "👍",
  "safe happy": "🛡️",
  "sad": "😢",
  "lonely": "🥺",
  "crying": "😭",
  "disappointed": "😞",
  "need comfort": "🤗",
  "mad": "😠",
  "angry": "😡",
  "frustrated": "😣",
  "too much": "⚠️",
  "need space": "🫧",
  "stop words": "🛑",
  "scared": "😨",
  "worried": "😟",
  "nervous": "😬",
  "unsafe": "⚠️",
  "loud dark": "🔊",
  "need safety": "🛡️",
  "hurt": "🤕",
  "sick": "🤒",
  "tired": "😴",
  "hungry thirsty": "🍽️",
  "temperature": "🌡️",
  "bathroom body": "🚽",
  "energy feelings": "⚡",
  "low energy": "😴",
  "high energy": "⚡",
  "wiggly": "🌀",
  "need break": "⏸️",
  "ready": "✅",
  "not ready": "⏸️",
  "calm tools": "😌",
  "quiet": "🤫",
  "space": "🫧",
  "breathing": "🌬️",
  "calm places": "🏠",
  "feeling needs": "🆘",
  "help needs": "🆘",
  "body needs": "🧍",
  "comfort needs": "🤗",
  "people needs": "👥",
  "stop needs": "🛑",
  "finish needs": "✅",
  "common fruit": "🍎",
  "berries": "🫐",
  "citrus": "🍊",
  "melon": "🍉",
  "tropical fruit": "🥭",
  "fruit cups": "🍎",
  "vegetables": "🥦",
  "crunchy produce": "🥕",
  "soft produce": "🍌",
  "potatoes": "🥔",
  "salads": "🥗",
  "dips": "🥫",
  "chips": "🍟",
  "gummies": "🍬",
  "crackers": "🫓",
  "cookies": "🍪",
  "bars": "🍫",
  "cold snacks": "🧊",
  "crunchy snacks": "🥨",
  "kid favorites": "⭐",
  "chicken meals": "🍗",
  "pizza meals": "🍕",
  "sandwich meals": "🥪",
  "pasta meals": "🍝",
  "soup rice": "🍲",
  "mexican foods": "🌮",
  "cereal": "🥣",
  "hot breakfast": "🥣",
  "bakery breakfast": "🥯",
  "eggs meat": "🍳",
  "breakfast drinks": "🥛",
  "breakfast snacks": "🍌",
  "water": "💧",
  "milk": "🥛",
  "juice": "🧃",
  "lemonade": "🍋",
  "smoothies": "🥤",
  "soda": "🥤",
  "hot drinks": "☕",
  "drink tools": "🥤",
  "candy": "🍬",
  "chocolate": "🍫",
  "cake": "🍰",
  "ice cream": "🍦",
  "pudding": "🍮",
  "frozen treats": "🍧",
  "hot meals": "🍲",
  "hot snacks": "🥨",
  "too hot": "🥵",
  "cold meals": "🥪",
  "cold drinks": "🧊",
  "frozen foods": "🍧",
  "too cold": "🥶",
  "cheerios": "🥣",
  "frosted flakes": "🥣",
  "lucky charms": "🥣",
  "fruit loops": "🥣",
  "cinnamon toast crunch": "🥣",
  "rice krispies": "🥣",
  "doritos": "🍟",
  "cheetos": "🍟",
  "pringles": "🍟",
  "goldfish": "🐟",
  "cheez it": "🫓",
  "oreos": "🍪",
  "oreo": "🍪",
  "m ms": "🍬",
  "skittles": "🍬",
  "welch's fruit snacks": "🍬",
  "scooby snacks": "🍬",
  "nutri grain bar": "🍫",
  "rice krispies treat": "🍫",
  "mandarin orange": "🍊",
  "clementine": "🍊",
  "grapefruit": "🍊",
  "lemon": "🍋",
  "lime": "🍋",
  "cantaloupe": "🍈",
  "honeydew": "🍈",
  "kiwi": "🥝",
  "coconut": "🥥",
  "papaya": "🥭",
  "ranch": "🥫",
  "hummus": "🥣",
  "cheese dip": "🧀",
  "salsa": "🥫",
  "guacamole": "🥑",
  "pizza rolls": "🍕",
  "hot pocket": "🥟",
  "lunchable": "🍱",

  // V5.19 generated full coverage for every current topic-tree label and leaf
  "adult": "🔹",
  "adults": "🔹",
  "all done hug": "🤗",
  "alone": "🥺",
  "animal crackers": "🫓",
  "awesome": "👍",
  "back hurts": "🤕",
  "baked potato": "🥔",
  "banana smoothie": "🥤",
  "be with me": "🙋",
  "beans and rice": "🍲",
  "bedroom": "😴",
  "bedtime": "🌙",
  "berry smoothie": "🥤",
  "berry yogurt": "🍎",
  "best friend": "👥",
  "better": "🔹",
  "big hug": "🤗",
  "birthday cake": "🍪",
  "blow on it": "🔹",
  "body": "🔹",
  "bottle": "🥤",
  "bottle water": "🥤",
  "bowl": "🥣",
  "boy": "👦",
  "bread": "📘",
  "breakfast biscuit": "🍳",
  "bring me": "🙋",
  "bubbles": "🔹",
  "buddy": "👥",
  "bus helper": "🚌",
  "butter": "🔹",
  "butter noodles": "🍝",
  "call": "🔹",
  "call dad": "👨",
  "call grandma": "👵",
  "call grandpa": "👴",
  "call mom": "👩",
  "car": "🚗",
  "caregiver": "👨‍👩‍👧",
  "cheese": "👤",
  "cheese puffs": "👤",
  "chewy": "👤",
  "chicken and rice": "🍗",
  "chicken soup": "🍗",
  "chili": "🍲",
  "chocolate bar": "🍫",
  "chocolate chip cookie": "🍪",
  "chocolate ice cream": "🍦",
  "chocolate pudding": "🔹",
  "cinnamon twists": "🔹",
  "class": "🧑‍🏫",
  "clean": "🔹",
  "close": "🫧",
  "coach": "🧑‍🏫",
  "coffee": "🔹",
  "cola": "🔹",
  "cold fruit": "🍎",
  "cold water": "🥤",
  "come back": "🙋",
  "comfortable": "🤗",
  "cone": "🍦",
  "cooked carrots": "🥕",
  "cough": "🤒",
  "count": "🔹",
  "cream cheese": "👤",
  "croissant": "🥞",
  "croutons": "🔹",
  "crunchy": "🍟",
  "cup water": "🥤",
  "dad help": "👨",
  "dance": "🎵",
  "danger": "⚠️",
  "dip": "🥫",
  "dipping sauce": "🥫",
  "driver": "🚌",
  "eat": "🍽️",
  "eggs and meat": "🍳",
  "everyone": "👥",
  "fan": "🔹",
  "fever": "🤒",
  "fidget": "🔹",
  "firefighter": "🛡️",
  "food": "🍽️",
  "foot hurts": "🤕",
  "fork": "🔹",
  "frosting": "🍪",
  "frozen fruit": "🍎",
  "frozen yogurt": "🥶",
  "fruit bar": "🍎",
  "fruit punch": "🍎",
  "fruit smoothie": "🥤",
  "gentle": "🔹",
  "girl": "👧",
  "give me": "🤲",
  "go away": "🔹",
  "go home": "🏠",
  "good afternoon": "🛑",
  "good job": "👍",
  "graham cracker": "🫓",
  "graham crackers": "🫓",
  "grape juice": "🥤",
  "great job": "🍽️",
  "grilled chicken": "🍗",
  "gummy bears": "🍬",
  "gummy worms": "🍬",
  "ham": "🔹",
  "hand hurts": "🤕",
  "hard": "😣",
  "have fun": "🔹",
  "he": "👤",
  "headphones": "📱",
  "help me breathe": "🍽️",
  "help please": "🆘",
  "hey": "👋",
  "hide": "👋",
  "home": "🏠",
  "home person": "👨‍👩‍👧",
  "hug dad": "👨",
  "hug mom": "👩",
  "hurt teeth": "🤕",
  "i am done": "✅",
  "i am happy": "😊",
  "i am here": "👤",
  "i am hurt": "🤕",
  "i am mad": "😠",
  "i am okay": "✅",
  "i am proud": "😌",
  "i am ready": "📘",
  "i am sad": "😢",
  "i am scared": "💖",
  "i am stuck": "😣",
  "i am tired": "😴",
  "i can": "💪",
  "i can't": "💪",
  "i care": "💖",
  "i did it": "🔹",
  "i didn't mean to": "🙋",
  "i don't understand": "🛑",
  "i feel good": "👍",
  "i feel happy": "😊",
  "i feel lonely": "🥺",
  "i feel mad": "😠",
  "i feel sad": "😢",
  "i feel scared": "💖",
  "i feel sick": "🤒",
  "i forgive you": "😔",
  "i go": "🔹",
  "i like that": "🔹",
  "i like you": "👉",
  "i love dad": "👨",
  "i love mom": "👩",
  "i love my family": "👨‍👩‍👧",
  "i need a break": "‼️",
  "i need bathroom": "🚽",
  "i need dad": "👨",
  "i need doctor": "🧑‍⚕️",
  "i need food": "🍽️",
  "i need friend": "👥",
  "i need help": "🆘",
  "i need medicine": "🧑‍⚕️",
  "i need mom": "👩",
  "i need nurse": "🧑‍⚕️",
  "i need quiet": "‼️",
  "i need rest": "😴",
  "i need teacher": "🧑‍🏫",
  "i need water": "🥤",
  "i tried": "🔹",
  "i want dad": "👨",
  "i want mom": "👩",
  "i want more": "✨",
  "i wanted that": "✨",
  "i worked hard": "😣",
  "ice cream sandwich": "🥪",
  "ice water": "🥤",
  "it's okay": "✅",
  "jelly": "🔹",
  "jelly sandwich": "🥪",
  "joke": "😜",
  "juice box": "🥤",
  "jump": "🔹",
  "keep going": "🔹",
  "kid": "🔹",
  "kids": "👥",
  "kind": "🔹",
  "later": "⏳",
  "laugh": "😜",
  "lid": "🔹",
  "little hug": "🤗",
  "lollipop": "🔹",
  "look": "👀",
  "love and care": "💖",
  "lunch": "🍽️",
  "lunch helper": "🍽️",
  "m and m's": "➕",
  "mandarin oranges": "🍎",
  "maybe": "🔹",
  "mcdonald's": "🍟",
  "me": "🙋",
  "mine": "🤲",
  "mixed fruit": "🍎",
  "mom help": "👩",
  "more berries": "🍎",
  "more cake": "🍪",
  "more candy": "🍬",
  "more cereal": "🥣",
  "more chicken": "🍗",
  "more chips": "🍟",
  "more cookie": "🍪",
  "more gummies": "🍬",
  "more juice": "🥤",
  "more lemonade": "🥤",
  "more milk": "🥤",
  "more please": "🙏",
  "more pudding": "➕",
  "more soda": "🥤",
  "more vegetables": "🥕",
  "more water": "🥤",
  "move": "🔹",
  "music off": "🎵",
  "my": "🙋",
  "my family": "👨‍👩‍👧",
  "my friend": "👥",
  "my friends": "👥",
  "my toy": "🎮",
  "nana": "👵",
  "nap": "😴",
  "neighbor": "👥",
  "new friend": "👥",
  "new person": "😬",
  "new place": "😬",
  "next": "🔁",
  "nice": "🥶",
  "nice work": "🥶",
  "no more": "🛑",
  "no one": "🛑",
  "no soda": "🥤",
  "no thank you": "🙏",
  "noodle soup": "🍝",
  "noodles": "🍝",
  "not close": "🫧",
  "not safe": "🛑",
  "now": "🛑",
  "office": "🥶",
  "old friend": "👥",
  "one more": "➕",
  "open": "🔹",
  "orange soda": "🥤",
  "pancake": "🍪",
  "pants": "🔹",
  "papa": "👴",
  "parent": "👨‍👩‍👧",
  "park": "🌳",
  "party": "🔹",
  "peaches cup": "🥤",
  "peanut butter sandwich": "🥪",
  "pee": "🚽",
  "pink lemonade": "🥤",
  "play friend": "👥",
  "playground": "🎮",
  "please help": "🆘",
  "please stay": "🙏",
  "police officer": "🥶",
  "poop": "🚽",
  "potato chips": "🥔",
  "pouch": "🔹",
  "privacy": "🚽",
  "protein bar": "🍫",
  "quiet room": "🫧",
  "read": "📘",
  "read with me": "📘",
  "really excited": "🤩",
  "recess": "🔹",
  "ritz": "🫓",
  "room": "🔹",
  "root beer": "🔹",
  "run": "🔹",
  "runny nose": "🛑",
  "safe hug": "🤗",
  "safe person": "🛡️",
  "safe place": "🛡️",
  "saltines": "🫓",
  "sausage": "🍳",
  "school nurse": "🧑‍🏫",
  "scrambled eggs": "🍳",
  "seat": "🍽️",
  "see you soon": "👋",
  "she": "👤",
  "show me": "👀",
  "sip": "🔹",
  "sit": "🔹",
  "sleep": "🌙",
  "slow breath": "🍽️",
  "smile": "😊",
  "snack bar": "🍫",
  "soft": "🔹",
  "soft voice": "🥶",
  "someone": "👥",
  "soup and rice": "🍲",
  "sour": "🔹",
  "spill": "🔹",
  "spoon": "🥣",
  "sprinkles": "🍪",
  "sprite": "🔹",
  "stand": "➕",
  "start": "🔹",
  "stay": "🔹",
  "strawberry ice cream": "🍦",
  "strawberry lemonade": "🥤",
  "strawberry milk": "🥤",
  "strawberry smoothie": "🥤",
  "sugar cookie": "🍪",
  "sweater": "🍽️",
  "swing": "🔹",
  "syrup": "🔹",
  "take it": "🤲",
  "talk": "🗣️",
  "tea": "🔹",
  "team": "👥",
  "tears": "😢",
  "tell me": "🙋",
  "that was good": "👍",
  "them": "👤",
  "they": "👋",
  "throw up": "🤒",
  "tissue": "🔹",
  "together": "👤",
  "toilet": "🚽",
  "too bright": "⚠️",
  "too close": "🫧",
  "tortilla chips": "🍟",
  "try": "💪",
  "try again": "🔁",
  "turkey": "🔹",
  "us": "👥",
  "vanilla ice cream": "🍦",
  "vanilla pudding": "🔹",
  "very mad": "😠",
  "visit": "🔹",
  "waffle": "🥞",
  "wait for me": "⏳",
  "wait please": "🙏",
  "wake up": "🌞",
  "walk": "🔹",
  "warm": "🥵",
  "warm cookie": "🍪",
  "warm milk": "🥤",
  "warm up": "🥵",
  "wash hands": "🚽",
  "watch": "🔹",
  "wave": "👋",
  "we": "👥",
  "wendy's": "👥",
  "what are you doing": "👉",
  "what happens": "😟",
  "where is dad": "👨",
  "where is mom": "👩",
  "white milk": "🥤",
  "wipe": "🔹",
  "with me": "🙋",
  "with mom": "👩",
  "work": "🔹",
  "wrapper": "🔹",
  "yes please": "🙏",
  "yogurt smoothie": "🥤",
  "you": "👉",
  "you are here": "👉",
  "you are nice": "🥶",
  "you did it": "👉",
  "you go": "👉",
  "you help me": "🆘",
  "you helped me": "🆘",
  "your": "👉",
  "your toy": "🎮",
  "yours": "👉",

  "i": "🙋", "want": "✨", "need": "‼️", "feel": "❤️", "am": "🔗", "can": "💪", "don't": "🚫", "like": "👍", "have": "🖐️", "see": "👀", "hear": "👂", "think": "🧠", "go": "➡️", "stop": "🛑", "get": "🫴", "do": "✅", "and": "➕", "because": "↪️", "but": "↔️", "to": "➡️", "with": "🤝", "then": "⏭️", "when": "🕒", "if": "❔", "so": "➡️", "yes": "✅"
};

function normalize(word = "") {
  return String(word)
    .toLowerCase()
    .replace(/&/g, " and ")
    .replace(/[^\w\s']/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function emojiFor(word = "") {
  const key = normalize(word);
  return SYMBOLS[key] || "⭐";
}

export default function SymbolImage({ word }) {
  const symbol = emojiFor(word);
  return (
    <div className="approvedSymbol" aria-hidden="true">
      <span style={{ fontSize: "2rem", lineHeight: 1 }}>{symbol}</span>
    </div>
  );
}
